### ISSUE TITLE
Babel config doesn't produce Node v4 compatible source

### ISSUE THREAD

**Issue by mzgoddard** [markfinger/env-hash#12]
The current babel config doesn't transform `...`. There may be some other issues, but that is the first one to trip up Node 4.

Encountered this while testing hard-source-webpack-plugin with env-hash. https://travis-ci.org/mzgoddard/hard-source-webpack-plugin/jobs/153682152

**Comment by mzgoddard** [comment]
Not sure what node versions you are looking to support. Figure I'd post this in case you are looking to support node's LTS version.

**Comment by markfinger** [comment]
I usually aim for the latest, but I'm happy to make an exception as env-hash is pretty small. I've published `1.1.0`, which is now passing the test suite under node v4.

**Comment by mzgoddard** [comment]
@markfinger Thanks!
